export const SET_USER_INFO = 'SET_USER_INFO';
export const ADD_USER_PROFILE = 'ADD_USER_PROFILE';
export const ADD_USER_PROFILE_SUCCESS = 'ADD_USER_PROFILE_SUCCESS';
export const ADD_USER_PROFILE_FAILED = 'ADD_USER_PROFILE_FAILED';
export const ADD_USER_PHOTO_SUCCESS = 'ADD_USER_PHOTO_SUCCESS';
