export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';
export const GET_MESSAGE_REQUEST = 'GET_MESSAGE_REQUEST';
export const GET_MESSAGE_REQUEST_SUCCESS = 'GET_MESSAGE_REQUEST_SUCCESS';
export const GET_MESSAGE_REQUEST_FAILED = 'GET_MESSAGE_REQUEST_FAILED';
