export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_REQUEST_SUCCESS = 'GET_USER_REQUEST_SUCCESS';
export const GET_USER_REQUEST_FAILED = 'GET_USER_REQUEST_FAILED';
export const SWIPED_NOPE_USER = 'SWIPED_NOPE_USER';
export const SWIPED_NOPE_USER_SUCCESS = 'SWIPED_NOPE_USER_SUCCESS';
export const SWIPED_NOPE_USER_FAILED = 'SWIPED_NOPE_USER_FAILED';
export const SWIPED_LIKE_USER = 'SWIPED_LIKE_USER';
export const SWIPED_LIKE_USER_SUCCESS = 'SWIPED_LIKE_USER_SUCCESS';
export const SWIPED_LIKE_USER_FAILED = 'SWIPED_LIKE_USER_FAILED';
export const GET_USER_PASSES_REQUEST = 'GET_USER_PASSES_REQUEST';
export const GET_USER_PASSES_REQUEST_SUCCESS =
  'GET_USER_PASSES_REQUEST_SUCCESS';
export const GET_USER_PASSES_REQUEST_FAILED = 'GET_USER_PASSES_REQUEST_FAILED';
export const GET_USER_SWIPED_REQUEST = 'GET_USER_SWIPED_REQUEST';
export const GET_USER_SWIPED_REQUEST_SUCCESS =
  'GET_USER_SWIPED_REQUEST_SUCCESS';
export const GET_USER_SWIPED_REQUEST_FAILED = 'GET_USER_SWIPED_REQUEST_FAILED';
export const GET_USER_LIKE_ME = 'GET_USER_LIKE_ME';
export const GET_USER_LIKE_ME_SUCCESS = 'GET_USER_LIKE_ME_SUCCESS';
export const GET_USER_LIKE_ME_FAILED = 'GET_USER_LIKE_ME_FAILED';
